import type { Metadata } from 'next';
import './globals.css';
import ReduxProvider from './providers/providers';
import { Header } from '@/components/layout/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased min-h-screen flex flex-col`}>
        <ReduxProvider>
          <Header />
          <main className="flex-1 pt-24 pb-12">{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
